# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RCA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCA
	
	pod 'Fabric', '~> 1.7.9'
	pod 'Crashlytics', '~> 3.10.5'
	pod 'Firebase/Core'
	pod 'SDWebImage', '~> 4.0'
   	pod 'IQKeyboardManagerSwift', '5.0.0'
	pod 'ReverseExtension'


  target 'RCATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RCAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
