# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceVision' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceVision
	pod 'SVProgressHUD'
    pod 'IQKeyboardManagerSwift'
     pod 'Fabric'
     pod 'Crashlytics'

end
